language: node_js
dist: trusty
node_js: '10.13'

cache: npm

install:


jobs:
  include:
    - stage: lint
    - script: ./scripts/install-and-lint.sh osrs-tracker-api
    - script: ./scripts/install-and-lint.sh osrs-tracker-app
    - script: ./scripts/install-and-lint.sh osrs-tracker-cron